version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: league-api
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456Aa*
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
