---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "go-app"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:latest"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        ports:
          - containerPort: 5432
            name: postgres

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres"
spec:
  ports:
    - port: 5432
  selector:
    app: "postgres"

