apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: go-app-dev
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  type: ClusterIPP
  ports:
  - port: 80
    targetPort: 3000
